
# This file is automatically generated, you probably don't want to edit this

addnewvarsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "addnewvarsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL, ...) {

            super$initialize(
                package="jmvtestnewvariables",
                name="addnewvars",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..newvar <- jmvcore::OptionOutput$new(
                "newvar")

            self$.addOption(private$..dep)
            self$.addOption(private$..newvar)
        }),
    active = list(
        dep = function() private$..dep$value,
        newvar = function() private$..newvar$value),
    private = list(
        ..dep = NA,
        ..newvar = NA)
)

addnewvarsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "addnewvarsResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        newvar = function() private$.items[["newvar"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Test Adding New Variables")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Test Adding New Variables"))
            self$add(jmvcore::Output$new(
                options=options,
                name="newvar",
                title="New Variable",
                varTitle="New Variable",
                varDescription="New Variable",
                measureType="continuous",
                clearWith=list(
                    "dep")))}))

addnewvarsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "addnewvarsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvtestnewvariables",
                name = "addnewvars",
                version = c(1,0,0),
                options = options,
                results = addnewvarsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Test Adding New Variables
#'
#' 
#' @param data .
#' @param dep .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$newvar} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
addnewvars <- function(
    data,
    dep) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("addnewvars requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- addnewvarsOptions$new(
        dep = dep)

    analysis <- addnewvarsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

